### ISSUE TITLE
How does a VCR controller work

### ISSUE THREAD

**Issue by vongohren** [bcgov/aries-vcr-issuer-agency#1]
I just got introduced to VCR by Stephen earlier today.
And I realized this is a VCR issuer.

Does it exist any drawings on how this works?
Is this part of a way to make credentails public? That was the thought that struck me atleast.

**Comment by esune** [comment]
Hey there! 🙂 

I do not have diagrams yet, since I am still developing and tweaking this. You can check-out the design document here: https://hackmd.io/@esune/BJxS4mC0P
For `aries-vcr` please check out: https://github.com/bcgov/aries-vcr

The way this is designed it is a managed ACA-Py agency, with a controller that acts as proxy for requests coming from consumers.
As you noticed, it is `aries-vcr` specific meaning it is targeted to entities that want to issue credential to an instance of `aries-vcr`. This is partially because of our current primary use-case, and partially to scope the work a bit in order to make it easier. It should however be easy/possible to integrate functionality to issue to other agents that are not targeting `aries-vcr`, this functionality will likely be coming sometime in the future.

**Comment by esune** [comment]
Closing, please feel free to reopen if necessary.
